### ISSUE TITLE
2016 Ext 2 ではエラーが出ます

### ISSUE THREAD

**Issue by myara13** [ShikouYamaue/SISideBar#2]
2016 Ext 2 ではエラーが出ます。

・原因
maya_ver 変数 は int( cmds.about(v=True) ) を使用していますが、2016 Extension 2 の場合は cmds.about(v=True)は 「"2016 Extension 2"」というストリングが帰ってくる為Integerに変換が出来くてエラーが出ます。

・対策
バージョン確認する際にmaya_ver_api変数を使えば良いかと思います。
因みに、2016 Extension 2 のAPI バージョンは 201650 です。

**Comment by ShikouYamaue** [comment]
ご指摘ありがとうございます！英語版とあわせて修正しました。
