### ISSUE TITLE
Crash changing component translation mode to local or global

### ISSUE THREAD

**Issue by miquelcampos** [ShikouYamaue/SISideBar#4]
Maya 2018 crash if we change the translation  mode from "component" to local or global in SiSideBar

Reproduction:

1. select 1 polygon
2. With translation marking menu, set translation to componet
3. change to global or local mode in siSideBar
4. instant Maya crash 

btw: Thanks for making this XSI tool for maya :)

**Comment by myara13** [comment]
I couldn't exactly reproduce that, but I do constantly get error messages and some crashes in 2018. Only in 2018 though.
BTW did you mean polygon face in your step 1?

// Error: IndexError: file ...\sisidebar\sisidebar_main.py line 311: list index out of range // 
// Warning: Python callback failed // 

-----------
念の為に訳しておきます。
1 ポリゴンを選択
2 移動のマーキングメニュー(W + クリック）でコンポーネントに変更
3 SISideBarでGlobalかLocalに設定変更
4 クラッシュ

自分ではその通りの再現が出来ませんでしたが、時々以上に書いてあるエラーメッセージが出ていてクラッシュしていました。

**Comment by miquelcampos** [comment]
Hola Martin!

Yes one polygon face.

I get also some error index if I try to open siSideBar with a transform manipulator (scale, rotate, translate tool) configured in component mode.
Component mode have new behavior in Maya 2018. Is the equivalent to Local model in component selection in Softimage.

**Comment by ShikouYamaue** [comment]
// Error: IndexError: file ...\sisidebar\sisidebar_main.py line 311: list index out of range //
// Warning: Python callback failed //
こちらは確認できました。
エラー回避できないか調べてみます！

関係ないですが、2016から法線の平均（AverageNormal）=Componentに置き換わってるみたいですね。気づいていませんでした。。

＞miquelcampos
Thank you for your report.
I could not reproduce the same symptoms.
I will investigate in detail.

**Comment by ShikouYamaue** [comment]
I tried to correct the behavior of component mode of 2018.
Can you try it in the latest version?

リストの範囲外エラーにも修正対応してみました～
2018からはコンポーネントモードのIDが9→10に変更されているのが原因でした。。

モード切替でMayaごとクラッシュするのはいまいち原因がはっきりしないですね。うむむ。

**Comment by miquelcampos** [comment]
Looks like is not crashing now.  :)
I will try more next week.
Thank you!
