### ISSUE TITLE
Refボタンにエラーが出ます

### ISSUE THREAD

**Issue by myara13** [ShikouYamaue/SISideBar#5]
Ref ボタンを使うと「# Error: NameError: file <maya console> line 1: name 'sisidebar_sub' is not defined # 」が出ます。

2462行のscriptJobでモジュールが見つからないということだと思いますので、importを足ししてみたら動きました。

"sisidebar_sub.set_reference(mode='"+mode+"')"
から
"from sisidebar import sisidebar_sub; sisidebar_sub.set_reference(mode='"+mode+"')"
に変更

**Comment by ShikouYamaue** [comment]
ご指摘ありがとうございます～。
ローカルでは事前インポートしてデバッグしてたので気づきませんでした…
該当箇所、修正更新しておきました！
