### ISSUE TITLE
移動ツールのペアレント-ローカルが逆

### ISSUE THREAD

**Issue by TAKE-3** [ShikouYamaue/SISideBar#6]
便利に使わせていただいております。
ただ、移動ツール選択時にローカルとペアレントの軸方向が逆なようです。
環境はMAYA2018です。
ご確認のほどよろしくお願いします。

**Comment by ShikouYamaue** [comment]
ご意見ありがとうございます！
Maya2015とSoftimageの対応するパラメータ名で合わせたのですが、
2016以降、表記がかわったようですね…
バージョンによって表記が変わるように調整してみます！

**Comment by TAKE-3** [comment]
素早いご返答ありがとうございます。
書いた後、説明があいまいだったので訂正させていただきます。
移動ツールを選択した際にSISideBarでローカルを選択するとペアレント軸での動作になり、SISideBarでペアレントを選択するとローカル軸での動作になります。
先ほどの記述だと軸の向きが逆と捉えられる可能性があって紛らわしいため、再度ご連絡させていただきました。
楽しみにさせていただきます！

**Comment by ShikouYamaue** [comment]
いわれて今気づいたんですが、SIのローカル＝Mayaのオブジェクトであって2015にあるローカルとは同じではないんですね…
これは並び順から変える必要がある気がしてきました。

**Comment by ShikouYamaue** [comment]
軸名修正して更新しました！それぞれのバージョンにあった命名になるようにしてあります。
ご確認くださいまし～

**Comment by TAKE-3** [comment]
ご対応ありがとうございます！
早速確認します！
