### ISSUE TITLE
setup.py に melインポートがありません。

### ISSUE THREAD

**Issue by myara13** [ShikouYamaue/SISideBar#7]
setup.py に mel がインポートされていない為、addRecentにエラーが出ます。

また、色々なシーンを連続で開いていくと毎回「保存しますか」が出て、「No」にクリックするのはしんどくなって来たので、自分のローカルに以下のコマンドを使って、シーンに変化がなければ保存のダイアログ出ずにシーンを開けます。

fileModified = cmds.file(q=True, modified=True)
if fileModified:
・・・

**Comment by ShikouYamaue** [comment]
ご指摘ありがとうございます！助かります！
対応して更新しておきましたのでご確認くださいませ。
