### ISSUE TITLE
posixpath.py line 70: 'NoneType' object has no attribute 'endswith'

### ISSUE THREAD

**Issue by utoplenick** [ShikouYamaue/SISideBar#8]
Trying to use on linux Maya2171 sp5: getting such error
Error: AttributeError: file /opt/Maya2017sp5/lib/python27.zip/posixpath.py line 70: 'NoneType' object has no attribute 'endswith'

**Comment by ShikouYamaue** [comment]
I am sorry, I do not support the Linux version and I do not know the cause.

**Comment by melMass** [comment]
Thanks a lot for these.

I managed to install the Sisidebar on both mac and linux by replacing each occurences of :

```python
os.getenv('MAYA_APP_dir')
```

by 

```python
os.getenv('MAYA_APP_DIR')
```
